# Site settings
title: MasterOfTheTiger's Blog
description: >
  MasterOfTheTiger's take on tech and other issues
baseurl: "/blog" # should be / if you build a global github page (eg o0ignition0o.github.io)
url: "https://mtiger.xyz" # The blog url you want to choose (you can use a github.io one, or pick your own hosted url :))
logo: "https://mtiger.xyz/icon.png" # This one is used as blog logo
twitter_username: MasterOTheTiger # Your twitter handle
github_username: MasterOfTheTiger # Your github handle

# Build settings
highlighter: rouge

root: "https://mtiger.xyz/blog" # Not really sure this is useful, need to cross check with blog writers :)
